name: Relatório de Bug
description: Registrar um relatório de bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reservar um tempo para preencher este relatório de bug!
  - type: input
    id: contact
    attributes:
      label: Dados de contato (opcional)
      description: Como podemos entrar em contato se precisarmos de mais informações?
      placeholder: ex. email@exemplo.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Descrição. O que aconteceu?
      description: Conte também o que você esperava que acontecesse.
      placeholder: Descreva o que você observou!
      value: "Ocorreu um bug!"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Passos para reproduzir
      description: Descreva os passos para reproduzir o problema
      placeholder: 1. Passo 1 ...
                   2. Passo 2 ...
                   3. Passo 3 ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamento esperado
      description: Descreva o comportamento esperado.
      placeholder: O comportamento esperado é ...
    validations:
      required: false
  - type: textarea
    id: actual-behavior
    attributes:
      label: Comportamento observado
      description: Descreva o comportamento observado.
      placeholder: O comportamento observado é ...
    validations:
      required: true
  - type: dropdown
    id: occurrence-frequency
    attributes:
      label: Ocorrência
      description: Com que frequência esse bug ocorre?
      options:
        - Frequentemente
        - Às vezes
        - Raramente
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log relevante
      description: Copie e cole qualquer log relevante. Ele será formatado automaticamente como código, então não é necessário usar aspas simples triplas.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Código de Conduta
      description: Ao enviar esta issue, você concorda em seguir nosso [Código de Conduta](../blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: Eu concordo em seguir o Código de Conduta deste projeto
          required: true
