name: Solicitação de Funcionalidade
description: Sugerir uma ideia para este projeto
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reservar um tempo para preencher esta solicitação de funcionalidade!
  - type: input
    id: contact
    attributes:
      label: Dados de contato (opcional)
      description: Como podemos entrar em contato se precisarmos de mais informações?
      placeholder: ex. email@exemplo.com
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: Resumo
      description: Descreva a funcionalidade solicitada.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivação
      description: Descreva a motivação por trás desta solicitação.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas
      description: Descreva as alternativas que você já considerou.
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: Contexto Adicional
  - type: checkboxes
    id: terms
    attributes:
      label: Código de Conduta
      description: Ao enviar esta issue, você concorda em seguir nosso [Código de Conduta](../blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: Eu concordo em seguir o Código de Conduta deste projeto
          required: true
